<?php

namespace Admin\GaleriaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GaleriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriaRepository extends EntityRepository
{
}
