<?php

namespace Admin\CommonBundle\Repository\Configuracao;

use Doctrine\Common\Cache\ApcCache;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Symfony\Component\Config\Definition\Exception\Exception;

/**
 * ConfiguracaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracaoRepository extends EntityRepository implements IConfiguracaoRepository
{

    public function porChave($key)
    {
        try{
            return $this
                ->createQueryBuilder("c")
                ->where("c.chave = :chave")
                ->setParameter("chave", $key)
                ->getQuery()
                ->useResultCache(true)
                ->getSingleResult()
                ;
        }catch (NoResultException $e){
            return null;
        }catch (NonUniqueResultException $e){
            return null;
        }catch (Exception $e){
            return null;
        }
    }

}
