<?php

namespace Admin\NoticiaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoticiaCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaCategoriaRepository extends EntityRepository implements INoticiaCategoriaRepository
{
}
