<?php

namespace Admin\CommonBundle\Repository\Banner;

use Doctrine\ORM\EntityRepository;

/**
 * LocalBannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalBannerRepository extends EntityRepository
{
}
