# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  admin_common.twig_extension.getclass:
    class: Admin\CommonBundle\Twig\Extension\CommonExtensionGetClass
    public: false
    tags:
      - { name: twig.extension }

# http://symfony.com/doc/master/bundles/KnpMenuBundle/index.html
# http://symfony.com/doc/master/bundles/KnpMenuBundle/menu_builder_service.html
  app.menu_builder:
    class: AppBundle\Menu\MenuBuilder
    arguments: ["@knp_menu.factory","@translator.default"]
    tags:
      - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
      - { name: knp_menu.menu_builder, method: createFooterMenu, alias: footer }

  admin.menu_builder:
    class: Admin\CommonBundle\Menu\MenuBuilder
    arguments: ["@knp_menu.factory","@translator.default","@security.authorization_checker"]
    tags:
      - { name: knp_menu.menu_builder, method: createHeaderMenu, alias: admin_header }
      - { name: knp_menu.menu_builder, method: createLeftMenu, alias: admin_left }