vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        imovel_image:
            uri_prefix:         /images/imovel
            upload_destination: %kernel.root_dir%/../web/images/imovel
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
