parameters:
    admin_storage.amazon_s3.class: AmazonS3
    admin_storage.photo_uploader.class: Admin\StorageBundle\Service\PhotoUploaderS3
    admin_storage.local_uploader.class: Admin\StorageBundle\Service\Uploader
    liip_imagine.filter.loader.crop.class: Liip\ImagineBundle\Imagine\Filter\Loader\CropFilterLoader

services:
    admin_storage.amazon_s3:
        class: %admin_storage.amazon_s3.class%
        arguments: [{ key: '%admin_storage.amazon_s3.aws_key%', secret: '%admin_storage.amazon_s3.aws_secret_key%' }]

    admin_storage.photo_uploader:
        class: %admin_storage.photo_uploader.class%
        arguments: ['@photo_storage_filesystem']

    admin_storage.local_uploader:
        class: %admin_storage.local_uploader.class%
        arguments: ['@knp_gaufrette.filesystem_map']

    shq.amazon.s3credentials:
        class: Aws\Credentials\Credentials
        arguments: ["%admin_storage.amazon_s3.aws_key%", "%admin_storage.amazon_s3.aws_secret_key%"]

    shq.amazon.s3:
        class: Aws\S3\S3Client
        arguments:
            - version: '2006-03-01'
              region: 'sa-east-1'
              credentials: "@shq.amazon.s3credentials"

    liip_imagine.filter.loader.crop:
        class: %liip_imagine.filter.loader.crop.class%
        tags:
            - { name: liip_imagine.filter.loader, loader: crop }
