<?php

namespace Admin\CommonBundle\Repository\Vitrine;

use Doctrine\ORM\EntityRepository;

/**
 * VitrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VitrineRepository extends EntityRepository implements IVitrineRepository
{

    public function findAllByOrder()
    {
        return $this
            ->createQueryBuilder("v")
            ->addOrderBy('v.ordem', 'DESC')
            ->addOrderBy('v.dtCreated', 'DESC')
            ->getQuery()
            ->useResultCache(true)
            ->getResult()
            ;
    }

    public function findAllByFilter()
    {
        $data = new \DateTime('now');
        //diferenca quando subir para o servidor
        //$data->sub(new \DateInterval('PT3M'));
        return $this
            ->createQueryBuilder("v")
            ->where("v.status = :status")
            ->andWhere(":hoje >= v.dtPublicacao OR v.dtPublicacao is NULL ")
            ->andWhere(":hoje <= v.dtExpiracao  OR vW.dtExpiracao is NULL ")
            ->setParameter("status", 1)
            ->setParameter("hoje", $data)
            ->addOrderBy('v.ordem', 'DESC')
            ->addOrderBy('v.dtCreated', 'DESC')
            ->setMaxResults(4)
            ->getQuery()
            ->useResultCache(true)
            ->getResult()
            ;
    }
}
